# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .ko_image import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_ko.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_ko.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "ko",
  "mod": "index/koImage",
  "fqn": "pulumi_ko",
  "classes": {
   "ko:index/koImage:KoImage": "KoImage"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "ko",
  "token": "pulumi:providers:ko",
  "fqn": "pulumi_ko",
  "class": "Provider"
 }
]
"""
)
