// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Container repositor to publish images to. Defaults to `KO_DOCKER_REPO` env var
func GetDockerRepo(ctx *pulumi.Context) string {
	return config.Get(ctx, "ko:dockerRepo")
}
